name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: use checkout for build
        run: |
          rm -f content
          rm -f themes/gbraad

      - uses: actions/checkout@v6
        with:
          repository: gbraad-pages/blog-content
          path: content
          ref: main

      - uses: actions/checkout@v6
        with:
          repository: gbraad-pages/blog-theme
          path: themes/gbraad
          ref: main

      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pelican markdown

      - name: Build site
        run: pelican -s publishconf.py

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: gh-pages
